### ISSUE TITLE
Unable to run closure.py script after installation from PyPI

### ISSUE THREAD

**Issue by wrobell** [RDFLib/OWL-RL#26] opened 2018-11-24 11:52 UTC
To reproduce on Linux

1. Install `owlrl` with `pip install --user owlrl`.
2. Run `~/.local/bin/closure.py`.
3. You will get the error like
```
$ ~/.local/bin/closure.py            
mksh: /home/wrobell/.local/bin/closure.py: No such file or directory
```

The reason for that is first line in the script
```
#!/home/flubba86/PycharmProjects/OWL-RL/venv/bin/python3
```

However in the repository the line is OK. It seems `owlrl` needs to be released without overrides from a local environment (BTW. new release is needed then as PyPI does not allow to re-upload file with same name and different checksum if I remember well).

As workaround run
```
python3 ~/.local/bin/closure.py
```

**Comment by nicholascar** [comment] 2018-11-27 23:10
Thanks for identifying, will try and update ASAP.

**Comment by ashleysommer** [comment] 2018-11-27 23:41
@wrobell Upon investigating, I've found this is caused by [_this bug_](https://github.com/pypa/setuptools/issues/994) in bdist_wheel. For some reason when building bdists with `python3 setup.py build bdist_wheel` it replaces:
`/usr/bin/env python3` with `/my/local/venv/bin/python3`.
Changing the command to `python3 setup.py bdist_wheel` without the `build` parameter fixes the issue. I'm surprised I haven't come across this issue before, because I've been building bdist wheel packages for several years now and not encountered this problem until now.

**Comment by ashleysommer** [comment] 2018-11-28 00:45
Fixed in https://github.com/RDFLib/OWL-RL/commit/29c4baf6ff91dd2135a5743098b09640c4c2905e

**Closed by ashleysommer** 2018-11-28 00:45 UTC
